version: "3.8"

services:
  react-app:
    container_name: react-jsx-app
    build:
      context: .
    tty: true
    volumes:
      - .:/app:cached
      - react_node_modules:/app/node_modules
    ports:
      - 5173:5173


volumes:
  react_node_modules: